// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/mall_seckill.proto

package mall_seckill

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Mallseckill service

func NewMallseckillEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Mallseckill service

type MallseckillService interface {
	Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error)
	ClientStream(ctx context.Context, opts ...client.CallOption) (Mallseckill_ClientStreamService, error)
	ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...client.CallOption) (Mallseckill_ServerStreamService, error)
	BidiStream(ctx context.Context, opts ...client.CallOption) (Mallseckill_BidiStreamService, error)
}

type mallseckillService struct {
	c    client.Client
	name string
}

func NewMallseckillService(name string, c client.Client) MallseckillService {
	return &mallseckillService{
		c:    c,
		name: name,
	}
}

func (c *mallseckillService) Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error) {
	req := c.c.NewRequest(c.name, "Mallseckill.Call", in)
	out := new(CallResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mallseckillService) ClientStream(ctx context.Context, opts ...client.CallOption) (Mallseckill_ClientStreamService, error) {
	req := c.c.NewRequest(c.name, "Mallseckill.ClientStream", &ClientStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &mallseckillServiceClientStream{stream}, nil
}

type Mallseckill_ClientStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*ClientStreamRequest) error
}

type mallseckillServiceClientStream struct {
	stream client.Stream
}

func (x *mallseckillServiceClientStream) Close() error {
	return x.stream.Close()
}

func (x *mallseckillServiceClientStream) Context() context.Context {
	return x.stream.Context()
}

func (x *mallseckillServiceClientStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *mallseckillServiceClientStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *mallseckillServiceClientStream) Send(m *ClientStreamRequest) error {
	return x.stream.Send(m)
}

func (c *mallseckillService) ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...client.CallOption) (Mallseckill_ServerStreamService, error) {
	req := c.c.NewRequest(c.name, "Mallseckill.ServerStream", &ServerStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &mallseckillServiceServerStream{stream}, nil
}

type Mallseckill_ServerStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*ServerStreamResponse, error)
}

type mallseckillServiceServerStream struct {
	stream client.Stream
}

func (x *mallseckillServiceServerStream) Close() error {
	return x.stream.Close()
}

func (x *mallseckillServiceServerStream) Context() context.Context {
	return x.stream.Context()
}

func (x *mallseckillServiceServerStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *mallseckillServiceServerStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *mallseckillServiceServerStream) Recv() (*ServerStreamResponse, error) {
	m := new(ServerStreamResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *mallseckillService) BidiStream(ctx context.Context, opts ...client.CallOption) (Mallseckill_BidiStreamService, error) {
	req := c.c.NewRequest(c.name, "Mallseckill.BidiStream", &BidiStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &mallseckillServiceBidiStream{stream}, nil
}

type Mallseckill_BidiStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*BidiStreamRequest) error
	Recv() (*BidiStreamResponse, error)
}

type mallseckillServiceBidiStream struct {
	stream client.Stream
}

func (x *mallseckillServiceBidiStream) Close() error {
	return x.stream.Close()
}

func (x *mallseckillServiceBidiStream) Context() context.Context {
	return x.stream.Context()
}

func (x *mallseckillServiceBidiStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *mallseckillServiceBidiStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *mallseckillServiceBidiStream) Send(m *BidiStreamRequest) error {
	return x.stream.Send(m)
}

func (x *mallseckillServiceBidiStream) Recv() (*BidiStreamResponse, error) {
	m := new(BidiStreamResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Mallseckill service

type MallseckillHandler interface {
	Call(context.Context, *CallRequest, *CallResponse) error
	ClientStream(context.Context, Mallseckill_ClientStreamStream) error
	ServerStream(context.Context, *ServerStreamRequest, Mallseckill_ServerStreamStream) error
	BidiStream(context.Context, Mallseckill_BidiStreamStream) error
}

func RegisterMallseckillHandler(s server.Server, hdlr MallseckillHandler, opts ...server.HandlerOption) error {
	type mallseckill interface {
		Call(ctx context.Context, in *CallRequest, out *CallResponse) error
		ClientStream(ctx context.Context, stream server.Stream) error
		ServerStream(ctx context.Context, stream server.Stream) error
		BidiStream(ctx context.Context, stream server.Stream) error
	}
	type Mallseckill struct {
		mallseckill
	}
	h := &mallseckillHandler{hdlr}
	return s.Handle(s.NewHandler(&Mallseckill{h}, opts...))
}

type mallseckillHandler struct {
	MallseckillHandler
}

func (h *mallseckillHandler) Call(ctx context.Context, in *CallRequest, out *CallResponse) error {
	return h.MallseckillHandler.Call(ctx, in, out)
}

func (h *mallseckillHandler) ClientStream(ctx context.Context, stream server.Stream) error {
	return h.MallseckillHandler.ClientStream(ctx, &mallseckillClientStreamStream{stream})
}

type Mallseckill_ClientStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*ClientStreamRequest, error)
}

type mallseckillClientStreamStream struct {
	stream server.Stream
}

func (x *mallseckillClientStreamStream) Close() error {
	return x.stream.Close()
}

func (x *mallseckillClientStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *mallseckillClientStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *mallseckillClientStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *mallseckillClientStreamStream) Recv() (*ClientStreamRequest, error) {
	m := new(ClientStreamRequest)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (h *mallseckillHandler) ServerStream(ctx context.Context, stream server.Stream) error {
	m := new(ServerStreamRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.MallseckillHandler.ServerStream(ctx, m, &mallseckillServerStreamStream{stream})
}

type Mallseckill_ServerStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*ServerStreamResponse) error
}

type mallseckillServerStreamStream struct {
	stream server.Stream
}

func (x *mallseckillServerStreamStream) Close() error {
	return x.stream.Close()
}

func (x *mallseckillServerStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *mallseckillServerStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *mallseckillServerStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *mallseckillServerStreamStream) Send(m *ServerStreamResponse) error {
	return x.stream.Send(m)
}

func (h *mallseckillHandler) BidiStream(ctx context.Context, stream server.Stream) error {
	return h.MallseckillHandler.BidiStream(ctx, &mallseckillBidiStreamStream{stream})
}

type Mallseckill_BidiStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*BidiStreamResponse) error
	Recv() (*BidiStreamRequest, error)
}

type mallseckillBidiStreamStream struct {
	stream server.Stream
}

func (x *mallseckillBidiStreamStream) Close() error {
	return x.stream.Close()
}

func (x *mallseckillBidiStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *mallseckillBidiStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *mallseckillBidiStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *mallseckillBidiStreamStream) Send(m *BidiStreamResponse) error {
	return x.stream.Send(m)
}

func (x *mallseckillBidiStreamStream) Recv() (*BidiStreamRequest, error) {
	m := new(BidiStreamRequest)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
