// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/mall_product.proto

package mall_product

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Mallproduct service

func NewMallproductEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Mallproduct service

type MallproductService interface {
	Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error)
	ClientStream(ctx context.Context, opts ...client.CallOption) (Mallproduct_ClientStreamService, error)
	ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...client.CallOption) (Mallproduct_ServerStreamService, error)
	BidiStream(ctx context.Context, opts ...client.CallOption) (Mallproduct_BidiStreamService, error)
}

type mallproductService struct {
	c    client.Client
	name string
}

func NewMallproductService(name string, c client.Client) MallproductService {
	return &mallproductService{
		c:    c,
		name: name,
	}
}

func (c *mallproductService) Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error) {
	req := c.c.NewRequest(c.name, "Mallproduct.Call", in)
	out := new(CallResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mallproductService) ClientStream(ctx context.Context, opts ...client.CallOption) (Mallproduct_ClientStreamService, error) {
	req := c.c.NewRequest(c.name, "Mallproduct.ClientStream", &ClientStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &mallproductServiceClientStream{stream}, nil
}

type Mallproduct_ClientStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*ClientStreamRequest) error
}

type mallproductServiceClientStream struct {
	stream client.Stream
}

func (x *mallproductServiceClientStream) Close() error {
	return x.stream.Close()
}

func (x *mallproductServiceClientStream) Context() context.Context {
	return x.stream.Context()
}

func (x *mallproductServiceClientStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *mallproductServiceClientStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *mallproductServiceClientStream) Send(m *ClientStreamRequest) error {
	return x.stream.Send(m)
}

func (c *mallproductService) ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...client.CallOption) (Mallproduct_ServerStreamService, error) {
	req := c.c.NewRequest(c.name, "Mallproduct.ServerStream", &ServerStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &mallproductServiceServerStream{stream}, nil
}

type Mallproduct_ServerStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*ServerStreamResponse, error)
}

type mallproductServiceServerStream struct {
	stream client.Stream
}

func (x *mallproductServiceServerStream) Close() error {
	return x.stream.Close()
}

func (x *mallproductServiceServerStream) Context() context.Context {
	return x.stream.Context()
}

func (x *mallproductServiceServerStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *mallproductServiceServerStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *mallproductServiceServerStream) Recv() (*ServerStreamResponse, error) {
	m := new(ServerStreamResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *mallproductService) BidiStream(ctx context.Context, opts ...client.CallOption) (Mallproduct_BidiStreamService, error) {
	req := c.c.NewRequest(c.name, "Mallproduct.BidiStream", &BidiStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &mallproductServiceBidiStream{stream}, nil
}

type Mallproduct_BidiStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*BidiStreamRequest) error
	Recv() (*BidiStreamResponse, error)
}

type mallproductServiceBidiStream struct {
	stream client.Stream
}

func (x *mallproductServiceBidiStream) Close() error {
	return x.stream.Close()
}

func (x *mallproductServiceBidiStream) Context() context.Context {
	return x.stream.Context()
}

func (x *mallproductServiceBidiStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *mallproductServiceBidiStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *mallproductServiceBidiStream) Send(m *BidiStreamRequest) error {
	return x.stream.Send(m)
}

func (x *mallproductServiceBidiStream) Recv() (*BidiStreamResponse, error) {
	m := new(BidiStreamResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Mallproduct service

type MallproductHandler interface {
	Call(context.Context, *CallRequest, *CallResponse) error
	ClientStream(context.Context, Mallproduct_ClientStreamStream) error
	ServerStream(context.Context, *ServerStreamRequest, Mallproduct_ServerStreamStream) error
	BidiStream(context.Context, Mallproduct_BidiStreamStream) error
}

func RegisterMallproductHandler(s server.Server, hdlr MallproductHandler, opts ...server.HandlerOption) error {
	type mallproduct interface {
		Call(ctx context.Context, in *CallRequest, out *CallResponse) error
		ClientStream(ctx context.Context, stream server.Stream) error
		ServerStream(ctx context.Context, stream server.Stream) error
		BidiStream(ctx context.Context, stream server.Stream) error
	}
	type Mallproduct struct {
		mallproduct
	}
	h := &mallproductHandler{hdlr}
	return s.Handle(s.NewHandler(&Mallproduct{h}, opts...))
}

type mallproductHandler struct {
	MallproductHandler
}

func (h *mallproductHandler) Call(ctx context.Context, in *CallRequest, out *CallResponse) error {
	return h.MallproductHandler.Call(ctx, in, out)
}

func (h *mallproductHandler) ClientStream(ctx context.Context, stream server.Stream) error {
	return h.MallproductHandler.ClientStream(ctx, &mallproductClientStreamStream{stream})
}

type Mallproduct_ClientStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*ClientStreamRequest, error)
}

type mallproductClientStreamStream struct {
	stream server.Stream
}

func (x *mallproductClientStreamStream) Close() error {
	return x.stream.Close()
}

func (x *mallproductClientStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *mallproductClientStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *mallproductClientStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *mallproductClientStreamStream) Recv() (*ClientStreamRequest, error) {
	m := new(ClientStreamRequest)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (h *mallproductHandler) ServerStream(ctx context.Context, stream server.Stream) error {
	m := new(ServerStreamRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.MallproductHandler.ServerStream(ctx, m, &mallproductServerStreamStream{stream})
}

type Mallproduct_ServerStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*ServerStreamResponse) error
}

type mallproductServerStreamStream struct {
	stream server.Stream
}

func (x *mallproductServerStreamStream) Close() error {
	return x.stream.Close()
}

func (x *mallproductServerStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *mallproductServerStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *mallproductServerStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *mallproductServerStreamStream) Send(m *ServerStreamResponse) error {
	return x.stream.Send(m)
}

func (h *mallproductHandler) BidiStream(ctx context.Context, stream server.Stream) error {
	return h.MallproductHandler.BidiStream(ctx, &mallproductBidiStreamStream{stream})
}

type Mallproduct_BidiStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*BidiStreamResponse) error
	Recv() (*BidiStreamRequest, error)
}

type mallproductBidiStreamStream struct {
	stream server.Stream
}

func (x *mallproductBidiStreamStream) Close() error {
	return x.stream.Close()
}

func (x *mallproductBidiStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *mallproductBidiStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *mallproductBidiStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *mallproductBidiStreamStream) Send(m *BidiStreamResponse) error {
	return x.stream.Send(m)
}

func (x *mallproductBidiStreamStream) Recv() (*BidiStreamRequest, error) {
	m := new(BidiStreamRequest)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
